name: olmo
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.11.13
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - torch==2.6.0
      - torchmetrics==1.8.1
      - ai2-olmo-core==2.1.0
      - ai2-olmo-eval==0.7.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.3.0
      - backports-tarfile==1.2.0
      - beaker-gantry==3.0.0
      - beaker-py==2.4.7
      - black==23.12.1
      - boltons==25.0.0
      - boto3==1.40.11
      - botocore==1.40.11
      - build==1.3.0
      - cached-path==1.7.3
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.2.1
      - click-help-colors==0.9.4
      - click-option-group==0.5.7
      - cryptography==45.0.6
      - datasets==4.0.0
      - dill==0.3.8
      - docutils==0.22
      - einops==0.8.1
      - face==24.0.0
      - filelock==3.19.1
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glom==24.11.0
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-cloud-core==2.4.3
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpcio==1.74.0
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - id==1.5.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - isort==5.12.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.2.1
      - jeepney==0.9.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.1
      - keyring==25.6.0
      - lightning-utilities==0.15.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgspec==0.19.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - mypy==1.3.0
      - mypy-extensions==1.1.0
      - necessary==0.4.3
      - networkx==3.5
      - nh3==0.3.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - packaging==25.0
      - pandas==2.3.1
      - pathspec==0.12.1
      - petname==2.6
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyproject-hooks==1.2.0
      - pytest==8.4.1
      - pytest-sphinx==0.6.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - readme-renderer==44.0
      - regex==2025.7.34
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - requirements-parser==0.13.0
      - rfc3986==2.0.0
      - rich==13.9.4
      - rsa==4.9.1
      - ruff==0.12.9
      - s3transfer==0.13.1
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - secretstorage==3.3.3
      - sentry-sdk==2.35.0
      - six==1.17.0
      - smart-open==7.3.0.post1
      - smashed==0.21.5
      - smmap==5.0.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - tqdm==4.67.1
      - transformers==4.52.4
      - triton==3.2.0
      - trouting==0.3.3
      - twine==6.1.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.21.1
      - wcwidth==0.2.13
      - wrapt==1.17.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/huayang_sakana_ai/.conda/envs/olmo
